# fly.toml app configuration file generated for bytebinder on 2023-07-04T20:43:40-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bytebinder"
primary_region = "iad"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "bytebinder.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
